image: zephyrprojectrtos/zephyr-build:latest
build:
  stage: build
  before_script:
    - rm -rf ../.west
    - west init -l .
    - west update
    - west zephyr-export
    - pip3 install -r ../zephyr/scripts/requirements-base.txt
  script:
    - source ../zephyr/zephyr-env.sh
    - west build -b beagleplay/cc1352p7 . -p
  artifacts:
    paths:
      - build/zephyr/zephyr.bin
